### ISSUE TITLE
Resolve upload conflicts

### ISSUE THREAD

**Issue by tordans** [rapideditor/rapid-sdk#166]
Same as https://github.com/ideditor/id-sdk/issues/165, this came up in a chat with @zlant about https://github.com/zlant/parking-lanes.

It would be perfect, if the logic to handle conflicts when uploading changes to OSM could be handled by a utility function from this repo.

Do you think this could happen some time?
Would it be helpful to collect ideas about input / return values?

**Comment by bhousel** [comment]
closing as stale again, but yes this would be awesome..

In Rapid last year, I did a big refactor of the core systems.. 
https://github.com/facebook/Rapid/pull/961

So now there is an uploader system that is responsible for gathering the edits into a changeset and checking for conflicts.
I'd like to over time move more of this common code for dealing with OSM from Rapid into this sdk so that other apps can reuse it.
